version: "3"
services:
  docker-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  rpc:
    image: ghcr.io/fuzzland/cached-eth-rpc:latest
    ports:
      - "8124:8124"
    environment:
      - ENDPOINTS=eth-chain=https://rpc.ankr.com/eth,bsc-chain=https://rpc.ankr.com/bsc
      - REDIS_URL=redis://docker-redis:6379
